name: jtg-spec-server

services:
  flask:
    image: jtg-spec-server:latest
    container_name: flask_app
    ports:
      - "5002:5002"
    env_file:
      - .env                     # 加载同目录下的 .env 文件
    restart: unless-stopped